name: VehiclesWASD
version: '${project.version}'
main: me.matsubara.vehicles.VehiclesPlugin
api-version: 1.17
author: Matsubara
description: '${project.description}'
load: STARTUP
depend:
  - packetevents
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - WorldGuard
  - Vault
  - Essentials
  - PlayerPoints
  - CMI
libraries:
  - org.apache.commons:commons-lang3:3.13.0
  - commons-io:commons-io:2.13.0

commands:
  vehicleswasd:
    description: main command.
    usage: /<command>
    aliases:
      - vwasd
      - vw